package paradroid.packets.mapGen;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Optional;

/**
 * @author dxf209
 *
 */
public class LoadMap {


    /**
     * Reads in an image and generates the GenMap based on this image
     * 
     * @param image	The image to be converted to a GenMap
     * @return		The GenMap generated by the image
     */
    public static GenMap readImage(BufferedImage image) {
        BufferedImage img = image;

    GenMap map = new GenMap(img);

        return map;
    }


    /**
     * Reads in an image specified by the path
     *
     * @param path	The path of the image to read
     * @return		The Optional GenMap that is generated from a valid image
     */
    public static Optional<GenMap> readImage(String path){
		BufferedImage img = null;
		try{
			// Read image from file
			File f = new File(path);
			img = ImageIO.read(new File(path));

			// Convert to GenMap
			GenMap map = new GenMap(img);
			
			return Optional.of(map);
					
		}catch(IOException e){
			System.out.println("IOException in image reading:");
			System.out.println(e.toString());

		}catch(Exception e){
			System.out.println("Exception in image reading:");
			System.out.println(e.toString());
		}
		return Optional.empty();
	}


}
